<?php
	$helper=$this->helper('centralprocessing');
	$auth_type = $helper->getAuthorizationType();
?>
<fieldset class="form-list">
    <ul id="payment_form_<?=$this->getMethodCode()?>" style="display:none">
        <li>
            <?=$helper->getInfo()?>
			
			<?php
				if( "AUTH" === $auth_type){
					echo '<br/><b><i> This will authorize you payment, and when it ships you will be invoices and your payment will be captured at that time. </i></b>';
				}
			?>
			
			
        </li>
    </ul>
</fieldset>