<?php
/**
 * @var $this Wsu_NetworkSecuritiesTheme_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>wsu-brand/bug-logotype.svg') no-repeat left top;padding-left:59px;min-height:59px;">
        <a href="https://github.com/washingtonstateuniversity/WSUMAGE-networksecurities" target="_blank" style="float:right;">
            <img src="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>wsu-brand/Github-fork-icon.svg" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>
        <h4><?php echo $this->helper('centralprocessing')->__('centralprocessing is a cybersource proxy'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('centralprocessing')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('centralprocessing')->__('#')); ?>" target="_blank"><?php echo $this->helper('centralprocessing')->__('here'); ?></a>.</p>
    </div>
    <p></p>
</div>